# Generated by Django 5.1.7 on 2025-03-06 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(blank=True, help_text='Nombre de la categoría', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Ingrese su nombre', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción ingresada por el usuario.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se creó la descripción.')),
                ('category', models.ForeignKey(blank=True, help_text='Categoría asignada a esta descripción.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nlp_app.category')),
            ],
        ),
    ]
