# Generated by Django 5.1.7 on 2025-03-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, help_text='True: Aprobado, False: Denegado')),
                ('formsending_id', models.ForeignKey(blank=True, help_text='Referencia a la descripción', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nlp_app.formsending')),
            ],
        ),
    ]
