# Generated by Django 5.1.7 on 2025-03-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_app', '0002_bypass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bypass',
            old_name='formsending_id',
            new_name='formsending',
        ),
    ]
